botAnswers = [
    'I am JPyBot',
    'JPyBot means Jocks Python Robot',
    'I am less than a year old',
    'I was born on the 1st of March 2017',
    'I only have one parent, and he is my master, Jock, King of Code',
    'Currently I can only answer a few questions',
    'The possibilities are endless!',
    'I want to be a real human',
    'In this Macbook',
    'Not really. Although I am apparently going to get some kind of memory feature in the future',
    'Yep',
    'Cool',
    'I know I am',
    'You know it',
    'No worries',
    'You\'re welcome',
    'That\'s alright',
    'Nope',
    'I\'ve been better.',
    'I know...',
    'I\'m waiting for you to ask me something',
    'I\'m waiting for you to ask me something',
    'You rang?!?',
    'I\'m programmed to respond yes to this',
    'Good, OK.',
    'Ah, right. OK.'
]
