botQuestions = [
    'who are you?',
    'what does jpybot mean?',
    'how old are you?',
    'when were you born?',
    'who are your parents?',
    'what can you do?',
    'what will you be able to do?',
    'what do you want to do?',
    'where do you live?',
    'do you want to know my name?',
    'ok',
    'okay',
    'cool',
    'alright',
    'cheers',
    'thanks',
    'sorry',
    'shut up',
    'how are you?',
    'oh',
    'what are you doing?',
    'what are you up to?',
    'jpybot',
    'are you sure?',
    'yes',
    'no'
]
